name: CI

on: [push]

jobs:
  build:
    name: Build OS ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ matrix.os }}-maven

      # We clean our artifacts from the repository just in case
      - name: clean powsybl cache
        shell: bash
        run: rm -rf ~/.m2/repository/com/powsybl

      - name: Build with Maven
        if: matrix.os == 'ubuntu-latest'
        run: mvn --batch-mode -Pjacoco install

      - name: Build with Maven
        if: matrix.os != 'ubuntu-latest'
        run: mvn --batch-mode install

      - name: Run SonarCloud analysis
        if: matrix.os == 'ubuntu-latest'
        run: >
          mvn --batch-mode -DskipTests sonar:sonar
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.organization=powsybl-ci-github
          -Dsonar.projectKey=com.powsybl:powsybl-core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # We clean some files to reduce the cache size because
      # we are over the 400MB limit (as of 2019-12-12 between 400MB and 500MB)
      # TODO is it better to remove some files or to split the cache in multiple files ?
      - name: clean powsybl cache
        shell: bash
        run: |
          rm -rf ~/.m2/repository/com/powsybl
          rm -rf ~/.m2/repository/org/wildfly/wildfly-dist/
